export const MOCK_PIVOT = [
  {
    name: "Argentina",
    year: 2020,
    continent: "South America",
    form: "Republic",
    gdp: 389.064,
    oil: 2.8,
    balance: -8.9,
    key: 1,
  },
  {
    name: "Argentina",
    year: 2021,
    continent: "South America",
    form: "Republic",
    gdp: 491.493,
    oil: 3.1,
    balance: -4.2,
    key: 2,
  },
  {
    name: "Australia",
    year: 2020,
    continent: "Australia",
    form: "Constitutional monarchy",
    gdp: 1326.9,
    oil: 15.2,
    balance: -35.1,
    key: 3,
  },
  {
    name: "Australia",
    year: 2021,
    continent: "Australia",
    form: "Constitutional monarchy",
    gdp: 1538.2,
    oil: 18.7,
    balance: -28.4,
    key: 4,
  },
  {
    name: "Germany",
    year: 2020,
    continent: "Europe",
    form: "Republic",
    gdp: 3806.0,
    oil: 90.5,
    balance: 215.3,
    key: 5,
  },
  {
    name: "Germany",
    year: 2021,
    continent: "Europe",
    form: "Republic",
    gdp: 4259.9,
    oil: 95.2,
    balance: 280.1,
    key: 6,
  },
  {
    name: "Vietnam",
    year: 2020,
    continent: "Asia",
    form: "Republic",
    gdp: 271.2,
    oil: 9.8,
    balance: 12.3,
    key: 7,
  },
  {
    name: "Vietnam",
    year: 2021,
    continent: "Asia",
    form: "Republic",
    gdp: 366.1,
    oil: 10.5,
    balance: 2.8,
    key: 8,
  },
];

export const MOCK_PIVOT_EMPTY: typeof MOCK_PIVOT = [];
