import {
  faBars,
  faCaretRight,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faCirclePlus,
  faExclamationTriangle,
  faEye,
  faFile,
  faFolder,
  faFolderOpen,
  faFolderPlus,
  faGreaterThan,
  faInfo,
  faMagnifyingGlass,
  faMinus,
  faPencil,
  faSortDown,
  faSpinner,
  faTimes,
  faTrash,
  faUpload,
  faUser,
  faX,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

import { faWindowRestore, faSquare } from "@fortawesome/free-regular-svg-icons";

export const fa = {
  faInfo,
  faPencil,
  faTrash,
  faFile,
  faFolder,
  faUpload,
  faFolderPlus,
  faChevronDown,
  faCheck,
  faExclamationTriangle,
  faSpinner,
  faUser,
  faSortDown,
  faCaretRight,
  faMagnifyingGlass,
  faGreaterThan,
  faFolderOpen,
  faX,
  faTimes,
  faMinus,
  faWindowRestore,
  faSquare,
  faXmark,
  faChevronLeft,
  faEye,
  faBars,
  faCirclePlus,
} as const;
